# Generated by Django 4.0.1 on 2022-01-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleapp',
            name='extra',
            field=models.BooleanField(null=True),
        ),
    ]
